### ISSUE TITLE
全屏自适应位置存在错误

### ISSUE THREAD

**Issue by Geequlim** [fairygui/FairyGUI-layabox#15]
如图在FairyGUI 编辑器中有左上和右下两张图标，分别按左上角和右下角设置关联
![image](https://user-images.githubusercontent.com/6964556/47081883-7b1b6b80-d23e-11e8-98e0-82b15e34a13a.png)

在Layaair中创建的界面按照文档中设置尺寸为舞台尺寸， 纵坐标没有对齐

![image](https://user-images.githubusercontent.com/6964556/47082158-52e03c80-d23f-11e8-8c73-8cd57a8bee01.png)

控制台通过  `fairygui.GRoot.inst.displayObject.getChildAt(0).y`  取到显示对象根节点的纵坐标是 `-145`, 将该值设为 0 后布局正常。

**Comment by xiaoguzhu** [comment]
这是laya的设置。laya的适配参数你没有选择填满全屏的。

**Comment by Geequlim** [comment]
在 setSize 时传入忽略轴心点为true 或者 在 setSize 后 通过setXY(0, 0) 可以解决此问题
