### ISSUE TITLE
GObject有bug 

### ISSUE THREAD

**Issue by qykings** [fairygui/FairyGUI-layabox#20]
![bug0001](https://user-images.githubusercontent.com/3444357/51491461-590b2980-1de9-11e9-858f-b4cea64eb130.png)

版本是最新layaair1.x

protected function handleXYChanged(): void {
			var xv:Number = this._x;
			var yv:Number = this._y+_yOffset;
			if(this._pivotAsAnchor)
			{					
				xv -= this._pivotX*this._width;
				yv -= this._pivotY*this._height;
			}
			if(_pixelSnapping)
			{
				xv = Math.round(xv);
				yv = Math.round(yv);
			}
			
                    //应该加上判断
			if(this._displayObject)
			{
				this._displayObject.pos(xv+this._pivotOffsetX, yv+this._pivotOffsetY);
			}
			
		}

**Comment by xiaoguzhu** [comment]
不需要加。不会空。

**Comment by qykings** [comment]
也许是他们模块写的有问题，我昨晚运行时发现this._displayObject是null ，导致不能调pos
