### ISSUE TITLE
在微信小游戏里面使用RichTextfield出现错误

### ISSUE THREAD

**Issue by MartinRood** [fairygui/FairyGUI-layabox#21]
在微信小游戏里面使用RichTextfield给text属性设置内容出现错误, 在网页中没有问题,例如:
直接初始化:
let  aRichTextField = new GRichTextField();
aRichTextField.setSize(100,100);
aRichTextField.text = "<a href='xxx'>Hello World</a>";
在微信的错误是:
gameThirdScriptError                     VM675:1
undfined
undefind

**Comment by xiaoguzhu** [comment]
这谁也猜不出来是什么。

**Comment by MartinRood** [comment]
> 这谁也猜不出来是什么。

如果有多一些出错信息,我也能明白这个是什么问题.现在layabox里面fairyGUI有很多问题需要解决

**Comment by xiaoguzhu** [comment]
出错信息是我说给就能给的吗？为什么你觉得是fairygui的问题，不是引擎的问题？

**Comment by fengzv** [comment]
微信把ThirdScript 用trycatch封装了。。你找到报错的哪个地方看 catch出来的报错就知道什么原因了。
我前一段遇见了这个问题也是两个undefind 然后查出来是需要引入xml解析库，微信环境本身不含这个。
laya的富文本是用html实现的，我估计你这个也是这个原因

**Comment by MartinRood** [comment]
> 微信把ThirdScript 用trycatch封装了。。你找到报错的哪个地方看 catch出来的报错就知道什么原因了。
> 我前一段遇见了这个问题也是两个undefind 然后查出来是需要引入xml解析库，微信环境本身不含这个。
> laya的富文本是用html实现的，我估计你这个也是这个原因

加个邮件聊聊吧
