### ISSUE TITLE
富文本宽度在laya中无效

### ISSUE THREAD

**Issue by gtd138** [fairygui/FairyGUI-layabox#22]
编辑器中设置好富文本的宽度，在Laya一直以一个默认的宽度显示。并且不是编辑器设置的宽度。宽度只能通过HTML方式设置。例如，<div style='width:378px;height:150px;color:#ff0000'>xxx</div>。

**Comment by gtd138** [comment]
`// 富文本工具类
export class RichTextHelper {
    private mRichTextObj:fairygui.GObject;
    private readonly mFeature:string = "<div style='width:{0}px;height:{1}px;color:{2}'>{3}</div>";
    private mText:string = "";
    public get Text():string{
        return this.mText;
    }
    public set Text(value:string){
        // 替换一下Unity里面的颜色标记
        var fixText = value.replace(/\[-\]/g, "</span>");
        fixText = fixText.replace(/\[/g, "<span style='color:#");
        fixText = fixText.replace(/\]/g, "'>");
        this.mText = fixText;
        var strWidth = this.mRichTextObj.width.toString();
        var strHeight = this.mRichTextObj.height.toString();
        this.mRichTextObj.text = this.FormatString(this.mFeature, strWidth, strHeight, this.mColor, this.mText);
    }

    public get Width():number{
        return this.mRichTextObj.width;
    }
    public set Width(value:number){
        this.mRichTextObj.width = value;
    }

    public get Height():number{
        return this.mRichTextObj.height;
    }
    public set Height(value:number){
        this.mRichTextObj.height = value;
    }

    private mColor:string = "";
    public get Color():string{
        return this.mColor;
    }
    public set Color(value:string){
        // 先清除所有#
        var fixColor = value.replace(/#/g, "");
        this.mColor = "#" + fixColor;
    }

    constructor(fobj:fairygui.GObject){
        this.mRichTextObj = fobj;
        this.mColor = this.mRichTextObj.asRichTextField.color;
    }

    // 格式化字符串
    private FormatString(str: string, ...val: string[]) {
        for (let index = 0; index < val.length; index++) {
          str = str.replace(`{${index}}`, val[index]);
        }
        return str;
    }
}`

写了一个工具类解决这个问题，这里分享一下。

**Comment by xiaoguzhu** [comment]
不能用width去设置一个控件的宽度，我觉得这是laya这个控件的缺陷，后续版本它应该会修正。
